version: "2"
services:
  zookeeper:
    image: "zookeeper:latest"
    ports:
      - "2181:2181"
  backend:
    image: "dubbo-samples-chain-backend:2.7.2"
    ports:
      - "20880:20880"
  middle:
    image: "dubbo-samples-chain-middle:2.7.2"
    ports:
      - "20881:20881"
